# Generated by Django 3.0.8 on 2020-08-12 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name="User's email")),
                ('created_ts', models.DateTimeField(default=datetime.datetime.now, verbose_name='User created timestamp')),
            ],
            options={
                'db_table': 'email_users',
            },
        ),
    ]
